version: 2

sources:
    - name: dev
      description: desarrolo local
      database: PC_DBT_DB
      schema: DBT_DVAQUERO
      tables:
        - name: IMPORT_CUSTOMER
        - name: RESUMEN_CUSTOMER
    - name: snowflake
      description: tabla de csv cargado
      database: SNOWFLAKE_SAMPLE_DATA
      schema: TPCH_SF1
      tables:
        - name: CUSTOMER
          description: tabla en produccion
