version: 2

sources:
    - name: jaffle_shop
      description: This is a replica of the Postgres database used by our app
      database: raw
      schema: jaffle_shop
      tables:
          - name: customers
            description: One record per customer.
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.
    - name: snowflake
      description: tabla de csv cargado
      database: SNOWFLAKE_SAMPLE_DATA
      schema: TPCH_SF1
      tables:
        - name: CUSTOMER
          description: tabla en produccion
